[project]
name = "pipeline-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["atria-core", "docling>=2.127.0"]

[tool.uv.sources]
atria-core = { git = "https://github.com/atriaml/atria_core.git" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pipeline_v2"]

[dependency-groups]
dev = [
    "coverage>=7.6.0",
    "mypy>=1.14.0",
    "pytest>=8.3.0",
    "ruff>=0.9.0",
    "types-tqdm>=4.67.0",
]

[tool.mypy]
ignore_missing_imports = true
